### ISSUE TITLE
Echo path impulse responses?

### ISSUE THREAD

**Issue by njb** [microsoft/AEC-Challenge#3]
In the folder https://github.com/microsoft/AEC-Challenge/tree/main/datasets/RIRs README, it says "This folder contains room impulse responses (RIRs) measured on real devices." I can only see the csv metadata file, however, and not the full impulse response files themselves. 

Any chance the full impulse response will be available? Maybe I just missed something?

Thank you for the awesome dataset!

**Comment by andosa** [comment]
The full responses are in files named *Sweep*

**Comment by njb** [comment]
Nice, thanks!

**Comment by njb** [comment]
@andosa, do the full responses exist for the synthetic dataset?

**Comment by andosa** [comment]
No, the sweep files are only in the real recordings dataset
