### ISSUE TITLE
How to get echo signal based on the  far end speech?

### ISSUE THREAD

**Issue by YoungJay0612** [microsoft/AEC-Challenge#4]
Hello guy, Sorry to bother you. But I have a doubt about the simulation form far end speech to the echo signal. As we know, it is a nonlinear distortion process, so I wonder how to simulate the nonlinear distortion and get the echo signal? 
Hopelly to hear from you, Thanks so much!

**Comment by andosa** [comment]
There is no out-of-the box solution for this. You can apply non-linear transformations on the waveform and apply RIR, or learn the NN models of distortion/RIR functions from the data
